#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Direnv
eval "$(direnv hook zsh)"

# NVM
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

# Elixir Version Manager ExEnv
export PATH="$HOME/.exenv/bin:$PATH"
eval "$(exenv init -)"

# YouTube DL alias
alias youtube-dl='docker run --rm -u $(id -u):$(id -g) -v $PWD:/data vimagick/youtube-dl'

# Overwrite ls with lsd
alias ls='lsd'

# Use highlight instead of cat
alias ocat=/bin/cat
alias cat="highlight $1 --out-format xterm256 -l --force -s anotherdark"

